### ISSUE TITLE
After apt-get update, not finding linux-headers

### ISSUE THREAD

**Issue by ifly53e** [elreydetoda/packer-kali_linux#29]
Anyone else seeing this?  After the script errored out and stopped, I re-ran vagrant up and I got a GUI login, but samurai:samurai did not work to login.

At this point, I ssh in with vagrant:vagrant, do a manual apt-get update, and try to add the packages with "sudo apt-get install  linux-compiler-gcc-6-x86 linux-headers-4.9.0-9-amd64
  linux-headers-4.9.0-9-common linux-kbuild-4.9"  but get the same errors as the script.

PS D:\samuraiwtf> vagrant up
Bringing machine 'samuraiwtf' up with 'virtualbox' provider...
==> samuraiwtf: Importing base box 'bento/debian-9'...
==> samuraiwtf: Matching MAC address for NAT networking...
==> samuraiwtf: Checking if box 'bento/debian-9' version '201907.07.0' is up to date...
==> samuraiwtf: Setting the name of the VM: SamuraiWTF-4.2.0
==> samuraiwtf: Clearing any previously set network interfaces...
==> samuraiwtf: Preparing network interfaces based on configuration...
    samuraiwtf: Adapter 1: nat
==> samuraiwtf: Forwarding ports...
    samuraiwtf: 22 (guest) => 2222 (host) (adapter 1)
==> samuraiwtf: Running 'pre-boot' VM customizations...
==> samuraiwtf: Booting VM...
==> samuraiwtf: Waiting for machine to boot. This may take a few minutes...
    samuraiwtf: SSH address: 127.0.0.1:2222
    samuraiwtf: SSH username: vagrant
    samuraiwtf: SSH auth method: private key
    samuraiwtf:
    samuraiwtf: Vagrant insecure key detected. Vagrant will automatically replace
    samuraiwtf: this with a newly generated keypair for better security.
    samuraiwtf:
    samuraiwtf: Inserting generated public key within guest...
    samuraiwtf: Removing insecure key from the guest if it's present...
    samuraiwtf: Key inserted! Disconnecting and reconnecting using new SSH key...
==> samuraiwtf: Machine booted and ready!
[samuraiwtf] GuestAdditions versions on your host (6.0.12) and guest (6.0.8) do not match.
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version (2.3-2).
The following additional packages will be installed:
  linux-compiler-gcc-6-x86 linux-headers-4.9.0-9-common linux-kbuild-4.9
The following NEW packages will be installed:
  linux-compiler-gcc-6-x86 linux-headers-4.9.0-9-amd64
  linux-headers-4.9.0-9-common linux-kbuild-4.9
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 9,592 kB of archives.
After this operation, 52.1 MB of additional disk space will be used.
Err:1 http://security.debian.org/debian-security stretch/updates/main amd64 linux-compiler-gcc-6-x86 amd64 4.9.168-1+deb
9u3
  404  Not Found [IP: 151.101.24.204 80]
Err:2 http://security.debian.org/debian-security stretch/updates/main amd64 linux-headers-4.9.0-9-common all 4.9.168-1+d
eb9u3
  404  Not Found [IP: 151.101.24.204 80]
Err:3 http://security.debian.org/debian-security stretch/updates/main amd64 linux-kbuild-4.9 amd64 4.9.168-1+deb9u3
  404  Not Found [IP: 151.101.24.204 80]
Err:4 http://security.debian.org/debian-security stretch/updates/main amd64 linux-headers-4.9.0-9-amd64 amd64 4.9.168-1+
deb9u3
  404  Not Found [IP: 151.101.24.204 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/l/linux/linux-compiler-gcc-6-x86_4.9.168
-1+deb9u3_amd64.deb  404  Not Found [IP: 151.101.24.204 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/l/linux/linux-headers-4.9.0-9-common_4.9
.168-1+deb9u3_all.deb  404  Not Found [IP: 151.101.24.204 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/l/linux/linux-kbuild-4.9_4.9.168-1+deb9u
3_amd64.deb  404  Not Found [IP: 151.101.24.204 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/l/linux/linux-headers-4.9.0-9-amd64_4.9.
168-1+deb9u3_amd64.deb  404  Not Found [IP: 151.101.24.204 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:5 http://security.debian.org/debian-security stretch/updates/main Sources [189 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [499 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:7 http://security.debian.org/debian-security stretch/updates/main Translation-en [220 kB]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main Sources.diff/Index [11.6 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages.diff/Index [11.6 kB]
Get:10 http://cdn-fastly.deb.debian.org/debian stretch-updates/main Translation-en.diff/Index [6,148 B]
Get:11 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2,365 B]
Get:12 http://cdn-fastly.deb.debian.org/debian stretch-updates/main Sources 2019-07-08-0821.07.pdiff [534 B]
Get:13 http://cdn-fastly.deb.debian.org/debian stretch-updates/main Sources 2019-08-14-2019.27.pdiff [554 B]
Get:14 http://cdn-fastly.deb.debian.org/debian stretch-updates/main Sources 2019-09-18-2012.01.pdiff [552 B]
Get:14 http://cdn-fastly.deb.debian.org/debian stretch-updates/main Sources 2019-09-18-2012.01.pdiff [552 B]
Get:15 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages 2019-07-08-0821.07.pdiff [445 B]
Get:16 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages 2019-08-14-2019.27.pdiff [339 B]
Get:17 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages 2019-09-18-2012.01.pdiff [337 B]
Get:17 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages 2019-09-18-2012.01.pdiff [337 B]
Get:18 http://cdn-fastly.deb.debian.org/debian stretch-updates/main Translation-en 2019-07-08-0821.07.pdiff [196 B]
Get:18 http://cdn-fastly.deb.debian.org/debian stretch-updates/main Translation-en 2019-07-08-0821.07.pdiff [196 B]
Get:19 http://cdn-fastly.deb.debian.org/debian stretch/main Sources [6,747 kB]
Get:20 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7,086 kB]
Get:21 http://cdn-fastly.deb.debian.org/debian stretch/main Translation-en [5,385 kB]
Fetched 20.5 MB in 24s (826 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-headers-4.9.0-9-amd64
E: Couldn't find any package by glob 'linux-headers-4.9.0-9-amd64'
E: Couldn't find any package by regex 'linux-headers-4.9.0-9-amd64'
==> samuraiwtf: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get install -y linux-headers-`uname -r` dkms

Stdout from the command:

Reading package lists...
Building dependency tree...
Reading state information...

Stderr from the command:

E: Unable to locate package linux-headers-4.9.0-9-amd64
E: Couldn't find any package by glob 'linux-headers-4.9.0-9-amd64'
E: Couldn't find any package by regex 'linux-headers-4.9.0-9-amd64'

**Comment by gobolabs** [comment]
Hello, I have the same issues since this morning... Unable to vagrant up ... 

Test boxes : 

debian/jessie64 
debian/buster64

**Comment by elreydetoda** [comment]
@ifly53e @gobolabs,

I am sorry, but I think you have the wrong project...from your logs you seem to be running [SamuraiWTF](https://github.com/SamuraiWTF/samuraiwtf) and this is a kali linux building repo.

:grin:

**Comment by elreydetoda** [comment]
there does seem to be a related issue though here: https://github.com/SamuraiWTF/samuraiwtf/issues/96#issuecomment-537599906

**Comment by ifly53e** [comment]
ugh...sorry about that...
